/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HomeRouteRouteImport } from './routes/_home/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as HomeIndexRouteImport } from './routes/_home/index'
import { Route as HomeTransactionsRouteImport } from './routes/_home/transactions'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAdminsRouteImport } from './routes/admin/admins'
import { Route as AdminChangePasswordRouteImport } from './routes/admin/change-password'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiWebhooksSwitchRouteImport } from './routes/api/webhooks/switch'

const HomeRouteRoute = HomeRouteRouteImport.update({
  id: '/_home',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeTransactionsRoute = HomeTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => HomeRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminsRoute = AdminAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminChangePasswordRoute = AdminChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksSwitchRoute = ApiWebhooksSwitchRouteImport.update({
  id: '/api/webhooks/switch',
  path: '/api/webhooks/switch',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof HomeIndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/transactions': typeof HomeTransactionsRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/change-password': typeof AdminChangePasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/webhooks/switch': typeof ApiWebhooksSwitchRoute
}
export interface FileRoutesByTo {
  '/transactions': typeof HomeTransactionsRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/change-password': typeof AdminChangePasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/': typeof HomeIndexRoute
  '/admin': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/webhooks/switch': typeof ApiWebhooksSwitchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_home': typeof HomeRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/_home/transactions': typeof HomeTransactionsRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/change-password': typeof AdminChangePasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/_home/': typeof HomeIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/webhooks/switch': typeof ApiWebhooksSwitchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/transactions'
    | '/admin/admins'
    | '/admin/change-password'
    | '/admin/login'
    | '/admin/'
    | '/api/auth/$'
    | '/api/webhooks/switch'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/transactions'
    | '/admin/admins'
    | '/admin/change-password'
    | '/admin/login'
    | '/'
    | '/admin'
    | '/api/auth/$'
    | '/api/webhooks/switch'
  id:
    | '__root__'
    | '/_home'
    | '/admin'
    | '/_home/transactions'
    | '/admin/admins'
    | '/admin/change-password'
    | '/admin/login'
    | '/_home/'
    | '/admin/'
    | '/api/auth/$'
    | '/api/webhooks/switch'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  HomeRouteRoute: typeof HomeRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiWebhooksSwitchRoute: typeof ApiWebhooksSwitchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_home': {
      id: '/_home'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof HomeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home/': {
      id: '/_home/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_home/transactions': {
      id: '/_home/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof HomeTransactionsRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/admins': {
      id: '/admin/admins'
      path: '/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AdminAdminsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/change-password': {
      id: '/admin/change-password'
      path: '/change-password'
      fullPath: '/admin/change-password'
      preLoaderRoute: typeof AdminChangePasswordRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/switch': {
      id: '/api/webhooks/switch'
      path: '/api/webhooks/switch'
      fullPath: '/api/webhooks/switch'
      preLoaderRoute: typeof ApiWebhooksSwitchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface HomeRouteRouteChildren {
  HomeTransactionsRoute: typeof HomeTransactionsRoute
  HomeIndexRoute: typeof HomeIndexRoute
}

const HomeRouteRouteChildren: HomeRouteRouteChildren = {
  HomeTransactionsRoute: HomeTransactionsRoute,
  HomeIndexRoute: HomeIndexRoute,
}

const HomeRouteRouteWithChildren = HomeRouteRoute._addFileChildren(
  HomeRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminAdminsRoute: typeof AdminAdminsRoute
  AdminChangePasswordRoute: typeof AdminChangePasswordRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAdminsRoute: AdminAdminsRoute,
  AdminChangePasswordRoute: AdminChangePasswordRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  HomeRouteRoute: HomeRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiWebhooksSwitchRoute: ApiWebhooksSwitchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
