/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AccountCreatedRouteImport } from './routes/account-created'
import { Route as AddBankAccountRouteImport } from './routes/add-bank-account'
import { Route as AddWalletAddressRouteImport } from './routes/add-wallet-address'
import { Route as BusinessVerificationFailedRouteImport } from './routes/business-verification-failed'
import { Route as BusinessVerifiedRouteImport } from './routes/business-verified'
import { Route as CreatePinRouteImport } from './routes/create-pin'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ForgotPinRouteImport } from './routes/forgot-pin'
import { Route as KybRouteImport } from './routes/kyb'
import { Route as MailSentRouteImport } from './routes/mail-sent'
import { Route as PayoutsRouteImport } from './routes/payouts'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ResetPinRouteImport } from './routes/reset-pin'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SigninPinRouteImport } from './routes/signin-pin'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AppBalancesRouteImport } from './routes/_app/balances'
import { Route as AppBeneficiariesRouteImport } from './routes/_app/beneficiaries'
import { Route as AppCollectionsRouteImport } from './routes/_app/collections'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppTransactionsRouteImport } from './routes/_app/transactions'
import { Route as KybBusinessDetailsRouteImport } from './routes/kyb/business-details'
import { Route as KybDirectorsAndUbosRouteImport } from './routes/kyb/directors-and-ubos'
import { Route as KybReviewAndSubmitRouteImport } from './routes/kyb/review-and-submit'
import { Route as KybUnderReviewRouteImport } from './routes/kyb/under-review'
import { Route as KybUploadDocumentsRouteImport } from './routes/kyb/upload-documents'
import { Route as PayoutsBatchRouteImport } from './routes/payouts/batch'
import { Route as PayoutsGroupsRouteImport } from './routes/payouts/groups'
import { Route as PayoutsNewRouteImport } from './routes/payouts/new'
import { Route as PayoutsReviewRouteImport } from './routes/payouts/review'
import { Route as SettingsPasskeysRouteImport } from './routes/settings_.passkeys'
import { Route as TransactionsRecipientsRouteImport } from './routes/transactions_.recipients'
import { Route as WithdrawalsConvertRouteImport } from './routes/withdrawals/convert'
import { Route as WithdrawalsWithdrawRouteImport } from './routes/withdrawals/withdraw'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppSettingsAppearanceRouteImport } from './routes/_app/settings/appearance'
import { Route as AppSettingsCompanyRouteImport } from './routes/_app/settings/company'
import { Route as AppSettingsProfileRouteImport } from './routes/_app/settings/profile'
import { Route as AppSettingsSecurityRouteImport } from './routes/_app/settings/security'
import { Route as AppSettingsTeamRouteImport } from './routes/_app/settings/team'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as PayoutsGroupsIndexRouteImport } from './routes/payouts/groups/index'
import { Route as PayoutsGroupsCreateRouteImport } from './routes/payouts/groups/create'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountCreatedRoute = AccountCreatedRouteImport.update({
  id: '/account-created',
  path: '/account-created',
  getParentRoute: () => rootRouteImport,
} as any)
const AddBankAccountRoute = AddBankAccountRouteImport.update({
  id: '/add-bank-account',
  path: '/add-bank-account',
  getParentRoute: () => rootRouteImport,
} as any)
const AddWalletAddressRoute = AddWalletAddressRouteImport.update({
  id: '/add-wallet-address',
  path: '/add-wallet-address',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessVerificationFailedRoute =
  BusinessVerificationFailedRouteImport.update({
    id: '/business-verification-failed',
    path: '/business-verification-failed',
    getParentRoute: () => rootRouteImport,
  } as any)
const BusinessVerifiedRoute = BusinessVerifiedRouteImport.update({
  id: '/business-verified',
  path: '/business-verified',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatePinRoute = CreatePinRouteImport.update({
  id: '/create-pin',
  path: '/create-pin',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPinRoute = ForgotPinRouteImport.update({
  id: '/forgot-pin',
  path: '/forgot-pin',
  getParentRoute: () => rootRouteImport,
} as any)
const KybRoute = KybRouteImport.update({
  id: '/kyb',
  path: '/kyb',
  getParentRoute: () => rootRouteImport,
} as any)
const MailSentRoute = MailSentRouteImport.update({
  id: '/mail-sent',
  path: '/mail-sent',
  getParentRoute: () => rootRouteImport,
} as any)
const PayoutsRoute = PayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPinRoute = ResetPinRouteImport.update({
  id: '/reset-pin',
  path: '/reset-pin',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninPinRoute = SigninPinRouteImport.update({
  id: '/signin-pin',
  path: '/signin-pin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBalancesRoute = AppBalancesRouteImport.update({
  id: '/balances',
  path: '/balances',
  getParentRoute: () => AppRoute,
} as any)
const AppBeneficiariesRoute = AppBeneficiariesRouteImport.update({
  id: '/beneficiaries',
  path: '/beneficiaries',
  getParentRoute: () => AppRoute,
} as any)
const AppCollectionsRoute = AppCollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsRoute = AppTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppRoute,
} as any)
const KybBusinessDetailsRoute = KybBusinessDetailsRouteImport.update({
  id: '/business-details',
  path: '/business-details',
  getParentRoute: () => KybRoute,
} as any)
const KybDirectorsAndUbosRoute = KybDirectorsAndUbosRouteImport.update({
  id: '/directors-and-ubos',
  path: '/directors-and-ubos',
  getParentRoute: () => KybRoute,
} as any)
const KybReviewAndSubmitRoute = KybReviewAndSubmitRouteImport.update({
  id: '/review-and-submit',
  path: '/review-and-submit',
  getParentRoute: () => KybRoute,
} as any)
const KybUnderReviewRoute = KybUnderReviewRouteImport.update({
  id: '/under-review',
  path: '/under-review',
  getParentRoute: () => KybRoute,
} as any)
const KybUploadDocumentsRoute = KybUploadDocumentsRouteImport.update({
  id: '/upload-documents',
  path: '/upload-documents',
  getParentRoute: () => KybRoute,
} as any)
const PayoutsBatchRoute = PayoutsBatchRouteImport.update({
  id: '/batch',
  path: '/batch',
  getParentRoute: () => PayoutsRoute,
} as any)
const PayoutsGroupsRoute = PayoutsGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => PayoutsRoute,
} as any)
const PayoutsNewRoute = PayoutsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PayoutsRoute,
} as any)
const PayoutsReviewRoute = PayoutsReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => PayoutsRoute,
} as any)
const SettingsPasskeysRoute = SettingsPasskeysRouteImport.update({
  id: '/settings_/passkeys',
  path: '/settings/passkeys',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRecipientsRoute = TransactionsRecipientsRouteImport.update({
  id: '/transactions_/recipients',
  path: '/transactions/recipients',
  getParentRoute: () => rootRouteImport,
} as any)
const WithdrawalsConvertRoute = WithdrawalsConvertRouteImport.update({
  id: '/withdrawals/convert',
  path: '/withdrawals/convert',
  getParentRoute: () => rootRouteImport,
} as any)
const WithdrawalsWithdrawRoute = WithdrawalsWithdrawRouteImport.update({
  id: '/withdrawals/withdraw',
  path: '/withdrawals/withdraw',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAppearanceRoute = AppSettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsCompanyRoute = AppSettingsCompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsProfileRoute = AppSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsSecurityRoute = AppSettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsTeamRoute = AppSettingsTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppSettingsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PayoutsGroupsIndexRoute = PayoutsGroupsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PayoutsGroupsRoute,
} as any)
const PayoutsGroupsCreateRoute = PayoutsGroupsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => PayoutsGroupsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account-created': typeof AccountCreatedRoute
  '/add-bank-account': typeof AddBankAccountRoute
  '/add-wallet-address': typeof AddWalletAddressRoute
  '/business-verification-failed': typeof BusinessVerificationFailedRoute
  '/business-verified': typeof BusinessVerifiedRoute
  '/create-pin': typeof CreatePinRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/forgot-pin': typeof ForgotPinRoute
  '/kyb': typeof KybRouteWithChildren
  '/mail-sent': typeof MailSentRoute
  '/payouts': typeof PayoutsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/reset-pin': typeof ResetPinRoute
  '/signin': typeof SigninRoute
  '/signin-pin': typeof SigninPinRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/balances': typeof AppBalancesRoute
  '/beneficiaries': typeof AppBeneficiariesRoute
  '/collections': typeof AppCollectionsRoute
  '/dashboard': typeof AppDashboardRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/transactions': typeof AppTransactionsRoute
  '/kyb/business-details': typeof KybBusinessDetailsRoute
  '/kyb/directors-and-ubos': typeof KybDirectorsAndUbosRoute
  '/kyb/review-and-submit': typeof KybReviewAndSubmitRoute
  '/kyb/under-review': typeof KybUnderReviewRoute
  '/kyb/upload-documents': typeof KybUploadDocumentsRoute
  '/payouts/batch': typeof PayoutsBatchRoute
  '/payouts/groups': typeof PayoutsGroupsRouteWithChildren
  '/payouts/new': typeof PayoutsNewRoute
  '/payouts/review': typeof PayoutsReviewRoute
  '/settings/passkeys': typeof SettingsPasskeysRoute
  '/transactions/recipients': typeof TransactionsRecipientsRoute
  '/withdrawals/convert': typeof WithdrawalsConvertRoute
  '/withdrawals/withdraw': typeof WithdrawalsWithdrawRoute
  '/settings/appearance': typeof AppSettingsAppearanceRoute
  '/settings/company': typeof AppSettingsCompanyRoute
  '/settings/profile': typeof AppSettingsProfileRoute
  '/settings/security': typeof AppSettingsSecurityRoute
  '/settings/team': typeof AppSettingsTeamRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/payouts/groups/create': typeof PayoutsGroupsCreateRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/payouts/groups/': typeof PayoutsGroupsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account-created': typeof AccountCreatedRoute
  '/add-bank-account': typeof AddBankAccountRoute
  '/add-wallet-address': typeof AddWalletAddressRoute
  '/business-verification-failed': typeof BusinessVerificationFailedRoute
  '/business-verified': typeof BusinessVerifiedRoute
  '/create-pin': typeof CreatePinRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/forgot-pin': typeof ForgotPinRoute
  '/kyb': typeof KybRouteWithChildren
  '/mail-sent': typeof MailSentRoute
  '/payouts': typeof PayoutsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/reset-pin': typeof ResetPinRoute
  '/signin': typeof SigninRoute
  '/signin-pin': typeof SigninPinRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/balances': typeof AppBalancesRoute
  '/beneficiaries': typeof AppBeneficiariesRoute
  '/collections': typeof AppCollectionsRoute
  '/dashboard': typeof AppDashboardRoute
  '/transactions': typeof AppTransactionsRoute
  '/kyb/business-details': typeof KybBusinessDetailsRoute
  '/kyb/directors-and-ubos': typeof KybDirectorsAndUbosRoute
  '/kyb/review-and-submit': typeof KybReviewAndSubmitRoute
  '/kyb/under-review': typeof KybUnderReviewRoute
  '/kyb/upload-documents': typeof KybUploadDocumentsRoute
  '/payouts/batch': typeof PayoutsBatchRoute
  '/payouts/new': typeof PayoutsNewRoute
  '/payouts/review': typeof PayoutsReviewRoute
  '/settings/passkeys': typeof SettingsPasskeysRoute
  '/transactions/recipients': typeof TransactionsRecipientsRoute
  '/withdrawals/convert': typeof WithdrawalsConvertRoute
  '/withdrawals/withdraw': typeof WithdrawalsWithdrawRoute
  '/settings/appearance': typeof AppSettingsAppearanceRoute
  '/settings/company': typeof AppSettingsCompanyRoute
  '/settings/profile': typeof AppSettingsProfileRoute
  '/settings/security': typeof AppSettingsSecurityRoute
  '/settings/team': typeof AppSettingsTeamRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/payouts/groups/create': typeof PayoutsGroupsCreateRoute
  '/settings': typeof AppSettingsIndexRoute
  '/payouts/groups': typeof PayoutsGroupsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/account-created': typeof AccountCreatedRoute
  '/add-bank-account': typeof AddBankAccountRoute
  '/add-wallet-address': typeof AddWalletAddressRoute
  '/business-verification-failed': typeof BusinessVerificationFailedRoute
  '/business-verified': typeof BusinessVerifiedRoute
  '/create-pin': typeof CreatePinRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/forgot-pin': typeof ForgotPinRoute
  '/kyb': typeof KybRouteWithChildren
  '/mail-sent': typeof MailSentRoute
  '/payouts': typeof PayoutsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/reset-pin': typeof ResetPinRoute
  '/signin': typeof SigninRoute
  '/signin-pin': typeof SigninPinRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_app/balances': typeof AppBalancesRoute
  '/_app/beneficiaries': typeof AppBeneficiariesRoute
  '/_app/collections': typeof AppCollectionsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/transactions': typeof AppTransactionsRoute
  '/kyb/business-details': typeof KybBusinessDetailsRoute
  '/kyb/directors-and-ubos': typeof KybDirectorsAndUbosRoute
  '/kyb/review-and-submit': typeof KybReviewAndSubmitRoute
  '/kyb/under-review': typeof KybUnderReviewRoute
  '/kyb/upload-documents': typeof KybUploadDocumentsRoute
  '/payouts/batch': typeof PayoutsBatchRoute
  '/payouts/groups': typeof PayoutsGroupsRouteWithChildren
  '/payouts/new': typeof PayoutsNewRoute
  '/payouts/review': typeof PayoutsReviewRoute
  '/settings_/passkeys': typeof SettingsPasskeysRoute
  '/transactions_/recipients': typeof TransactionsRecipientsRoute
  '/withdrawals/convert': typeof WithdrawalsConvertRoute
  '/withdrawals/withdraw': typeof WithdrawalsWithdrawRoute
  '/_app/settings/appearance': typeof AppSettingsAppearanceRoute
  '/_app/settings/company': typeof AppSettingsCompanyRoute
  '/_app/settings/profile': typeof AppSettingsProfileRoute
  '/_app/settings/security': typeof AppSettingsSecurityRoute
  '/_app/settings/team': typeof AppSettingsTeamRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/payouts/groups/create': typeof PayoutsGroupsCreateRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/payouts/groups/': typeof PayoutsGroupsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account-created'
    | '/add-bank-account'
    | '/add-wallet-address'
    | '/business-verification-failed'
    | '/business-verified'
    | '/create-pin'
    | '/forgot-password'
    | '/forgot-pin'
    | '/kyb'
    | '/mail-sent'
    | '/payouts'
    | '/reset-password'
    | '/reset-pin'
    | '/signin'
    | '/signin-pin'
    | '/signup'
    | '/verify-email'
    | '/balances'
    | '/beneficiaries'
    | '/collections'
    | '/dashboard'
    | '/settings'
    | '/transactions'
    | '/kyb/business-details'
    | '/kyb/directors-and-ubos'
    | '/kyb/review-and-submit'
    | '/kyb/under-review'
    | '/kyb/upload-documents'
    | '/payouts/batch'
    | '/payouts/groups'
    | '/payouts/new'
    | '/payouts/review'
    | '/settings/passkeys'
    | '/transactions/recipients'
    | '/withdrawals/convert'
    | '/withdrawals/withdraw'
    | '/settings/appearance'
    | '/settings/company'
    | '/settings/profile'
    | '/settings/security'
    | '/settings/team'
    | '/api/auth/$'
    | '/payouts/groups/create'
    | '/settings/'
    | '/payouts/groups/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account-created'
    | '/add-bank-account'
    | '/add-wallet-address'
    | '/business-verification-failed'
    | '/business-verified'
    | '/create-pin'
    | '/forgot-password'
    | '/forgot-pin'
    | '/kyb'
    | '/mail-sent'
    | '/payouts'
    | '/reset-password'
    | '/reset-pin'
    | '/signin'
    | '/signin-pin'
    | '/signup'
    | '/verify-email'
    | '/balances'
    | '/beneficiaries'
    | '/collections'
    | '/dashboard'
    | '/transactions'
    | '/kyb/business-details'
    | '/kyb/directors-and-ubos'
    | '/kyb/review-and-submit'
    | '/kyb/under-review'
    | '/kyb/upload-documents'
    | '/payouts/batch'
    | '/payouts/new'
    | '/payouts/review'
    | '/settings/passkeys'
    | '/transactions/recipients'
    | '/withdrawals/convert'
    | '/withdrawals/withdraw'
    | '/settings/appearance'
    | '/settings/company'
    | '/settings/profile'
    | '/settings/security'
    | '/settings/team'
    | '/api/auth/$'
    | '/payouts/groups/create'
    | '/settings'
    | '/payouts/groups'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/account-created'
    | '/add-bank-account'
    | '/add-wallet-address'
    | '/business-verification-failed'
    | '/business-verified'
    | '/create-pin'
    | '/forgot-password'
    | '/forgot-pin'
    | '/kyb'
    | '/mail-sent'
    | '/payouts'
    | '/reset-password'
    | '/reset-pin'
    | '/signin'
    | '/signin-pin'
    | '/signup'
    | '/verify-email'
    | '/_app/balances'
    | '/_app/beneficiaries'
    | '/_app/collections'
    | '/_app/dashboard'
    | '/_app/settings'
    | '/_app/transactions'
    | '/kyb/business-details'
    | '/kyb/directors-and-ubos'
    | '/kyb/review-and-submit'
    | '/kyb/under-review'
    | '/kyb/upload-documents'
    | '/payouts/batch'
    | '/payouts/groups'
    | '/payouts/new'
    | '/payouts/review'
    | '/settings_/passkeys'
    | '/transactions_/recipients'
    | '/withdrawals/convert'
    | '/withdrawals/withdraw'
    | '/_app/settings/appearance'
    | '/_app/settings/company'
    | '/_app/settings/profile'
    | '/_app/settings/security'
    | '/_app/settings/team'
    | '/api/auth/$'
    | '/payouts/groups/create'
    | '/_app/settings/'
    | '/payouts/groups/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AccountCreatedRoute: typeof AccountCreatedRoute
  AddBankAccountRoute: typeof AddBankAccountRoute
  AddWalletAddressRoute: typeof AddWalletAddressRoute
  BusinessVerificationFailedRoute: typeof BusinessVerificationFailedRoute
  BusinessVerifiedRoute: typeof BusinessVerifiedRoute
  CreatePinRoute: typeof CreatePinRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ForgotPinRoute: typeof ForgotPinRoute
  KybRoute: typeof KybRouteWithChildren
  MailSentRoute: typeof MailSentRoute
  PayoutsRoute: typeof PayoutsRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResetPinRoute: typeof ResetPinRoute
  SigninRoute: typeof SigninRoute
  SigninPinRoute: typeof SigninPinRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  SettingsPasskeysRoute: typeof SettingsPasskeysRoute
  TransactionsRecipientsRoute: typeof TransactionsRecipientsRoute
  WithdrawalsConvertRoute: typeof WithdrawalsConvertRoute
  WithdrawalsWithdrawRoute: typeof WithdrawalsWithdrawRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-created': {
      id: '/account-created'
      path: '/account-created'
      fullPath: '/account-created'
      preLoaderRoute: typeof AccountCreatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-bank-account': {
      id: '/add-bank-account'
      path: '/add-bank-account'
      fullPath: '/add-bank-account'
      preLoaderRoute: typeof AddBankAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-wallet-address': {
      id: '/add-wallet-address'
      path: '/add-wallet-address'
      fullPath: '/add-wallet-address'
      preLoaderRoute: typeof AddWalletAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-verification-failed': {
      id: '/business-verification-failed'
      path: '/business-verification-failed'
      fullPath: '/business-verification-failed'
      preLoaderRoute: typeof BusinessVerificationFailedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-verified': {
      id: '/business-verified'
      path: '/business-verified'
      fullPath: '/business-verified'
      preLoaderRoute: typeof BusinessVerifiedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-pin': {
      id: '/create-pin'
      path: '/create-pin'
      fullPath: '/create-pin'
      preLoaderRoute: typeof CreatePinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-pin': {
      id: '/forgot-pin'
      path: '/forgot-pin'
      fullPath: '/forgot-pin'
      preLoaderRoute: typeof ForgotPinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kyb': {
      id: '/kyb'
      path: '/kyb'
      fullPath: '/kyb'
      preLoaderRoute: typeof KybRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mail-sent': {
      id: '/mail-sent'
      path: '/mail-sent'
      fullPath: '/mail-sent'
      preLoaderRoute: typeof MailSentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payouts': {
      id: '/payouts'
      path: '/payouts'
      fullPath: '/payouts'
      preLoaderRoute: typeof PayoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-pin': {
      id: '/reset-pin'
      path: '/reset-pin'
      fullPath: '/reset-pin'
      preLoaderRoute: typeof ResetPinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin-pin': {
      id: '/signin-pin'
      path: '/signin-pin'
      fullPath: '/signin-pin'
      preLoaderRoute: typeof SigninPinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/balances': {
      id: '/_app/balances'
      path: '/balances'
      fullPath: '/balances'
      preLoaderRoute: typeof AppBalancesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/beneficiaries': {
      id: '/_app/beneficiaries'
      path: '/beneficiaries'
      fullPath: '/beneficiaries'
      preLoaderRoute: typeof AppBeneficiariesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/collections': {
      id: '/_app/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof AppCollectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transactions': {
      id: '/_app/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AppTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/kyb/business-details': {
      id: '/kyb/business-details'
      path: '/business-details'
      fullPath: '/kyb/business-details'
      preLoaderRoute: typeof KybBusinessDetailsRouteImport
      parentRoute: typeof KybRoute
    }
    '/kyb/directors-and-ubos': {
      id: '/kyb/directors-and-ubos'
      path: '/directors-and-ubos'
      fullPath: '/kyb/directors-and-ubos'
      preLoaderRoute: typeof KybDirectorsAndUbosRouteImport
      parentRoute: typeof KybRoute
    }
    '/kyb/review-and-submit': {
      id: '/kyb/review-and-submit'
      path: '/review-and-submit'
      fullPath: '/kyb/review-and-submit'
      preLoaderRoute: typeof KybReviewAndSubmitRouteImport
      parentRoute: typeof KybRoute
    }
    '/kyb/under-review': {
      id: '/kyb/under-review'
      path: '/under-review'
      fullPath: '/kyb/under-review'
      preLoaderRoute: typeof KybUnderReviewRouteImport
      parentRoute: typeof KybRoute
    }
    '/kyb/upload-documents': {
      id: '/kyb/upload-documents'
      path: '/upload-documents'
      fullPath: '/kyb/upload-documents'
      preLoaderRoute: typeof KybUploadDocumentsRouteImport
      parentRoute: typeof KybRoute
    }
    '/payouts/batch': {
      id: '/payouts/batch'
      path: '/batch'
      fullPath: '/payouts/batch'
      preLoaderRoute: typeof PayoutsBatchRouteImport
      parentRoute: typeof PayoutsRoute
    }
    '/payouts/groups': {
      id: '/payouts/groups'
      path: '/groups'
      fullPath: '/payouts/groups'
      preLoaderRoute: typeof PayoutsGroupsRouteImport
      parentRoute: typeof PayoutsRoute
    }
    '/payouts/new': {
      id: '/payouts/new'
      path: '/new'
      fullPath: '/payouts/new'
      preLoaderRoute: typeof PayoutsNewRouteImport
      parentRoute: typeof PayoutsRoute
    }
    '/payouts/review': {
      id: '/payouts/review'
      path: '/review'
      fullPath: '/payouts/review'
      preLoaderRoute: typeof PayoutsReviewRouteImport
      parentRoute: typeof PayoutsRoute
    }
    '/settings_/passkeys': {
      id: '/settings_/passkeys'
      path: '/settings/passkeys'
      fullPath: '/settings/passkeys'
      preLoaderRoute: typeof SettingsPasskeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions_/recipients': {
      id: '/transactions_/recipients'
      path: '/transactions/recipients'
      fullPath: '/transactions/recipients'
      preLoaderRoute: typeof TransactionsRecipientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/withdrawals/convert': {
      id: '/withdrawals/convert'
      path: '/withdrawals/convert'
      fullPath: '/withdrawals/convert'
      preLoaderRoute: typeof WithdrawalsConvertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/withdrawals/withdraw': {
      id: '/withdrawals/withdraw'
      path: '/withdrawals/withdraw'
      fullPath: '/withdrawals/withdraw'
      preLoaderRoute: typeof WithdrawalsWithdrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/appearance': {
      id: '/_app/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AppSettingsAppearanceRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/company': {
      id: '/_app/settings/company'
      path: '/company'
      fullPath: '/settings/company'
      preLoaderRoute: typeof AppSettingsCompanyRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/profile': {
      id: '/_app/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AppSettingsProfileRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/security': {
      id: '/_app/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AppSettingsSecurityRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/team': {
      id: '/_app/settings/team'
      path: '/team'
      fullPath: '/settings/team'
      preLoaderRoute: typeof AppSettingsTeamRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payouts/groups/': {
      id: '/payouts/groups/'
      path: '/'
      fullPath: '/payouts/groups/'
      preLoaderRoute: typeof PayoutsGroupsIndexRouteImport
      parentRoute: typeof PayoutsGroupsRoute
    }
    '/payouts/groups/create': {
      id: '/payouts/groups/create'
      path: '/create'
      fullPath: '/payouts/groups/create'
      preLoaderRoute: typeof PayoutsGroupsCreateRouteImport
      parentRoute: typeof PayoutsGroupsRoute
    }
  }
}

interface AppSettingsRouteChildren {
  AppSettingsAppearanceRoute: typeof AppSettingsAppearanceRoute
  AppSettingsCompanyRoute: typeof AppSettingsCompanyRoute
  AppSettingsProfileRoute: typeof AppSettingsProfileRoute
  AppSettingsSecurityRoute: typeof AppSettingsSecurityRoute
  AppSettingsTeamRoute: typeof AppSettingsTeamRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsAppearanceRoute: AppSettingsAppearanceRoute,
  AppSettingsCompanyRoute: AppSettingsCompanyRoute,
  AppSettingsProfileRoute: AppSettingsProfileRoute,
  AppSettingsSecurityRoute: AppSettingsSecurityRoute,
  AppSettingsTeamRoute: AppSettingsTeamRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppBalancesRoute: typeof AppBalancesRoute
  AppBeneficiariesRoute: typeof AppBeneficiariesRoute
  AppCollectionsRoute: typeof AppCollectionsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppTransactionsRoute: typeof AppTransactionsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBalancesRoute: AppBalancesRoute,
  AppBeneficiariesRoute: AppBeneficiariesRoute,
  AppCollectionsRoute: AppCollectionsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppTransactionsRoute: AppTransactionsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface KybRouteChildren {
  KybBusinessDetailsRoute: typeof KybBusinessDetailsRoute
  KybDirectorsAndUbosRoute: typeof KybDirectorsAndUbosRoute
  KybReviewAndSubmitRoute: typeof KybReviewAndSubmitRoute
  KybUnderReviewRoute: typeof KybUnderReviewRoute
  KybUploadDocumentsRoute: typeof KybUploadDocumentsRoute
}

const KybRouteChildren: KybRouteChildren = {
  KybBusinessDetailsRoute: KybBusinessDetailsRoute,
  KybDirectorsAndUbosRoute: KybDirectorsAndUbosRoute,
  KybReviewAndSubmitRoute: KybReviewAndSubmitRoute,
  KybUnderReviewRoute: KybUnderReviewRoute,
  KybUploadDocumentsRoute: KybUploadDocumentsRoute,
}

const KybRouteWithChildren = KybRoute._addFileChildren(KybRouteChildren)

interface PayoutsGroupsRouteChildren {
  PayoutsGroupsCreateRoute: typeof PayoutsGroupsCreateRoute
  PayoutsGroupsIndexRoute: typeof PayoutsGroupsIndexRoute
}

const PayoutsGroupsRouteChildren: PayoutsGroupsRouteChildren = {
  PayoutsGroupsCreateRoute: PayoutsGroupsCreateRoute,
  PayoutsGroupsIndexRoute: PayoutsGroupsIndexRoute,
}

const PayoutsGroupsRouteWithChildren = PayoutsGroupsRoute._addFileChildren(
  PayoutsGroupsRouteChildren,
)

interface PayoutsRouteChildren {
  PayoutsBatchRoute: typeof PayoutsBatchRoute
  PayoutsGroupsRoute: typeof PayoutsGroupsRouteWithChildren
  PayoutsNewRoute: typeof PayoutsNewRoute
  PayoutsReviewRoute: typeof PayoutsReviewRoute
}

const PayoutsRouteChildren: PayoutsRouteChildren = {
  PayoutsBatchRoute: PayoutsBatchRoute,
  PayoutsGroupsRoute: PayoutsGroupsRouteWithChildren,
  PayoutsNewRoute: PayoutsNewRoute,
  PayoutsReviewRoute: PayoutsReviewRoute,
}

const PayoutsRouteWithChildren =
  PayoutsRoute._addFileChildren(PayoutsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AccountCreatedRoute: AccountCreatedRoute,
  AddBankAccountRoute: AddBankAccountRoute,
  AddWalletAddressRoute: AddWalletAddressRoute,
  BusinessVerificationFailedRoute: BusinessVerificationFailedRoute,
  BusinessVerifiedRoute: BusinessVerifiedRoute,
  CreatePinRoute: CreatePinRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ForgotPinRoute: ForgotPinRoute,
  KybRoute: KybRouteWithChildren,
  MailSentRoute: MailSentRoute,
  PayoutsRoute: PayoutsRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  ResetPinRoute: ResetPinRoute,
  SigninRoute: SigninRoute,
  SigninPinRoute: SigninPinRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  SettingsPasskeysRoute: SettingsPasskeysRoute,
  TransactionsRecipientsRoute: TransactionsRecipientsRoute,
  WithdrawalsConvertRoute: WithdrawalsConvertRoute,
  WithdrawalsWithdrawRoute: WithdrawalsWithdrawRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
